export const GET_HOTEL_START = "GET_HOTEL_START";
export const GET_HOTEL = "GET_HOTEL";
export const GET_HOTEL_FAIL = "GET_HOTEL_FAIL";
export const SET_HOTEL_DETAILS = "SET_HOTEL_DETAILS";
export const GET_HOTEL_ROOMS_START = "GET_HOTEL_ROOMS_START";
export const GET_HOTEL_ROOMS = "GET_HOTEL_ROOMS";
export const GET_HOTEL_ROOMS_FAIL = "GET_HOTEL_ROOMS_FAIL";
